export const LOAD_BLOCKCHAIN_DATA_REQ = "LOAD_BLOCKCHAIN_DATA_REQ";
export const LOAD_BLOCKCHAIN_DATA_SUCCESS = "LOAD_BLOCKCHAIN_DATA_SUCCESS";

export const CREATE_TODO_REQ = "CREATE_TODO_REQ";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";

export const TOGGLE_TODO_REQ = "TOGGLE_TODO_REQ";
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";

export const LIST_TODO_REQ = "LIST_TODO_REQ";
export const LIST_TODO_SUCCESS = "LIST_TODO_SUCCESS";
